[tool.poetry]
name = "binary-classification"
version = "0.1.0"
description = ""
authors = ["Russell Kim <russellkim98@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
jupyterlab = "^4.0.9"
streamlit = "^1.28.2"
scikit-learn = "^1.3.2"
python-dotenv = "^1.0.0"
scipy = "^1.11.4"
plotly = "^5.18.0"
pytest = "^7.4.3"
ipdb = "^0.13.13"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
